const express= require("express")
var cors = require('cors')
const path= require("path")
require('dotenv').config();
const router= require("./routes/user.route")
const material_router= require("./routes/matrial.route")
const appoiment_router= require("./routes/appoiment.route")
const transaction_router= require("./routes/transaction.router")
const bodyParser = require('body-parser')
const ErrorHandler = require("./middleware/errorHandler")
require("./conn/conn")
const Port = process.env.PORT
const app = express()
app.use(express.json())
app.use(express.static(path.join(__dirname,'public')))
app.use(bodyParser.urlencoded({extended:true}))
app.use(cors())
app.use(bodyParser.json())
app.use(router)
app.use(material_router)
app.use(appoiment_router)
app.use(transaction_router)
app.use(ErrorHandler)
app.get("/home",(req,res)=>{
    res.send("this is home page")
})
 app.listen(Port,()=>{
    console.log(`port running on ${Port}`)
})
